-- Seed data for testing Agenda Viva VO

-- Sample entities
INSERT INTO entitats (nom, slug, descripcio, web, email, verificada) VALUES
  ('Espai Cultural Granollers', 'espai-cultural-granollers', 'Centre cultural amb diversos tallers i activitats per a totes les edats', 'https://www.granollers.cat/cultura', 'cultura@granollers.cat', true),
  ('Club Esportiu Mollet', 'club-esportiu-mollet', 'Club esportiu amb múltiples seccions: futbol, bàsquet, natació', 'https://www.cemollet.cat', 'info@cemollet.cat', true),
  ('Escola de Música La Garriga', 'escola-musica-garriga', 'Escola municipal de música amb professors titulats', 'https://www.lagarriga.cat/musica', 'musica@lagarriga.cat', true);

-- Sample activities
INSERT INTO activitats (
  entitat_id,
  nom,
  slug,
  descripcio,
  curs,
  tipologies,
  tipologia_principal,
  subtipologia,
  quan_es_fa,
  edat_min,
  edat_max,
  edat_text,
  municipi,
  barri_zona,
  dies,
  horari,
  preu,
  tags,
  nd_score,
  nd_nivell,
  nd_justificacio,
  nd_indicadors_positius,
  nd_indicadors_negatius,
  nd_recomanacions,
  nd_confianca,
  nd_verificat_per,
  confianca_global,
  estat,
  destacada,
  created_by
) VALUES
  (
    (SELECT id FROM entitats WHERE slug = 'espai-cultural-granollers'),
    'Taller de pintura infantil',
    'taller-pintura-infantil-granollers',
    'Taller de pintura per a nens i nenes de 6 a 10 anys. Treballem diferents tècniques (aquarel·la, acrílic, tempera) en grups reduïts de 8 alumnes màxim. Cada sessió és un projecte complet que els nens es poden endur a casa. Ambient tranquil i respectuós amb el ritme de cada infant.',
    '2025-2026',
    '[{"codi": "arts", "score": 95, "justificacio": "Activitat específica de pintura i arts plàstiques"}]'::jsonb,
    'arts',
    'pintura',
    'setmanal',
    6,
    10,
    '6 a 10 anys',
    'granollers',
    'Centre',
    'Dimarts',
    '17:00 a 18:30',
    '40€/mes',
    ARRAY['petit_grup', 'material_inclòs'],
    4,
    'Bastant adequat',
    'Grups molt reduïts (8 alumnes màxim) i metodologia respectuosa amb el ritme individual. Ambient tranquil ideal per a concentració.',
    ARRAY['Grups reduïts (màx 8 persones)', 'Ritme flexible i adaptable', 'Espai tranquil i poc sorollós'],
    ARRAY[]::text[],
    ARRAY['Consultar possibilitat de suport addicional si cal'],
    75,
    'revisat',
    90,
    'publicada',
    false,
    'seed'
  ),
  (
    (SELECT id FROM entitats WHERE slug = 'club-esportiu-mollet'),
    'Futbol base setmanal',
    'futbol-base-mollet',
    'Entrenaments de futbol per a nens i nenes de 8 a 14 anys. Dos entrenaments setmanals i partit el cap de setmana. Equips formats per edats. Fem èmfasi en el treball en equip i el fair play més que en la competició.',
    '2025-2026',
    '[{"codi": "esports", "score": 100, "justificacio": "Activitat esportiva de futbol"}]'::jsonb,
    'esports',
    'futbol',
    'setmanal',
    8,
    14,
    '8 a 14 anys',
    'mollet',
    'Zona esportiva',
    'Dimarts i dijous + partit dissabte',
    '18:00 a 19:30',
    '50€/mes',
    ARRAY['aire_lliure', 'competitiu'],
    2,
    'Pot tenir barreres',
    'El futbol és un esport d''equip amb grups grans (15-20 jugadors), ambient sorollós i amb component competitiu. Pot ser estimulant per a alguns però exigent socialment.',
    ARRAY['Èmfasi en fair play i diversió'],
    ARRAY['Grups grans (15-20 persones)', 'Ambient sorollós', 'Alta demanda de comunicació social', 'Competició present'],
    ARRAY['Consultar amb els entrenadors sobre grups recreatius sense competició', 'Possibilitat d''entrenar sense jugar partits competitius'],
    65,
    'revisat',
    85,
    'publicada',
    false,
    'seed'
  ),
  (
    (SELECT id FROM entitats WHERE slug = 'escola-musica-garriga'),
    'Classes de violí individuals',
    'violi-individual-garriga',
    'Classes individuals de violí per a nens a partir de 7 anys. Metodologia adaptada a cada alumne amb professor titulat. Durada: 30 minuts setmanals. Incloem llenguatge musical bàsic. Ambient tranquil amb sales insonoritzades. Possibilitat de fer proves gratuïtes abans d''inscriure''s.',
    '2025-2026',
    '[{"codi": "musica", "score": 100, "justificacio": "Classes d''instrument musical"}]'::jsonb,
    'musica',
    'instrument',
    'setmanal',
    7,
    null,
    'A partir de 7 anys',
    'la-garriga',
    'Centre',
    'A convenir',
    'Horari flexible',
    '60€/mes',
    ARRAY['individual', 'flexibilitat_horari', 'proves_gratuites'],
    5,
    'Molt adequat',
    'Classes completament individualitzades amb ritme totalment adaptat a l''alumne. Espai tranquil i insonoritzat. Professor amb experiència en nens amb diferents necessitats. Proves gratuïtes permeten conèixer l''activitat sense compromís.',
    ARRAY['Atenció individualitzada (1 alumne)', 'Ritme totalment flexible', 'Espai tranquil i insonoritzat', 'Professionals amb formació específica', 'Proves gratuïtes disponibles', 'Horari flexible'],
    ARRAY[]::text[],
    ARRAY['Excel·lent opció per a qualsevol perfil'],
    90,
    'confirmat_entitat',
    95,
    'publicada',
    true,
    'seed'
  );

-- Sample scraping sources
INSERT INTO fonts_scraping (nom, tipus, url, activa) VALUES
  ('Ajuntament Granollers - Activitats', 'web', 'https://www.granollers.cat/activitats', true),
  ('Ajuntament Mollet - Joventut', 'web', 'https://www.molletvalles.cat/joventut', true),
  ('Xarxa Esplais Catalans', 'web', 'https://www.esplais.cat', false);
